efashion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('accounts/', include('allauth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import (
    landing,
    category_item,
    product_detail,
    add_to_cart,
    remove_from_cart,
    remove_single_from_cart,
    search_item,
    CheckoutView,
    cart_view,
    add_address,
    add_coupon,
    payment,
    response,
    success,
    myorders,
    returnorder,
    trackorder,
    aboutUs,
    contactUs,
    privacy_policy,
    terms_con,
    refund_return,
)



urlpatterns = [
    path('', landing, name="landing"),
    path('search/', search_item, name="search"),
    path('cart/', cart_view, name="cart"),
    path('payment/', payment,name="payment"),
    path('success/<int:id>', success,name="success"),
    path('response/', response, name="response"),
    path('add-coupon/', add_coupon, name="add-coupon"),
    path('add-address/', add_address, name="add-address"),
    path('category/<int:id>/', category_item, name="category"),
    path('product-detail/<int:id>/', product_detail, name="product-detail"),
    path('add-to-cart/<int:id>/', add_to_cart, name="add-to-cart"),
    path('remove-from-cart/<int:id>/<str:size>', remove_from_cart, name="remove-from-cart"),
    path('remove-single-from-cart/<int:id>/', remove_single_from_cart, name="remove-single-from-cart"),
    path('checkout/', CheckoutView.as_view(), name="checkout"),
    path('myorders/', myorders, name="myorder"),
    path('return/', returnorder, name="return"),
    path('track/', trackorder, name="track"),
    path('contact/', contactUs, name="contact"),
    path('about/', aboutUs, name="about"),
    path('privacy_policy/', privacy_policy, name="policy"),
    path('terms/', terms_con, name="terms"),
    path('return_policy/', refund_return, name="returnPolicy"),
    # Authentication System 
    # path('signup/', SignUpSystem, name="Signin"),
    # path('login/', LoginSystem, name="Login"),
    # path('logout/', logoutUser, name="Logout")

]

products/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
'''
category
item
orderitem
order
address
couponcode
refund
metaTags
Review
'''

class Available_For(models.Model):
    title = models.CharField(max_length=200)
    img = models.ImageField(upload_to='Available For', null=True)

    def __str__(self):
     return self.title

class Category(models.Model):
    title = models.CharField(max_length=200)
    poster = models.ImageField(upload_to='Category Poster', null=True)
    _for = models.ForeignKey(Available_For, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f'{self._for}-{self.title}'


class Crousal(models.Model):
    title = models.CharField(max_length=200)
    img = models.ImageField(upload_to='Crousal Image')

    def __str__(self):
        return self.title

class Item(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    p_name = models.CharField(max_length=200)
    p_image = models.ImageField(upload_to='Items')
    second_img = models.ImageField(upload_to='Second Img', null=True, blank=True)
    third_img = models.ImageField(upload_to='Third Img', null=True, blank=True)
    p_price = models.IntegerField()
    p_dis_price = models.IntegerField(null=True, blank=True)
    p_desc = models.TextField()
    thirty_four_size = models.BooleanField(null=True)
    small_size = models.BooleanField(null=True)
    medium_size = models.BooleanField(null=True)
    large_size = models.BooleanField(null=True)
    xl_size = models.BooleanField(null=True)
    xxl_size = models.BooleanField(null=True)
    p_slug = models.SlugField(max_length=200)

    def __str__(self):
        return self.p_name


class OrderItem(models.Model):
    SIZE_OPTION = [
        ('34','34'),
        ('S', 'S'),
        ('M', 'M'),
        ('L', 'L'),
        ('XL', 'XL'),
        ('2XL', '2XL'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orderitems')
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    size = models.CharField(max_length=100, choices=SIZE_OPTION, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.quantity} of {self.item.p_name} at {self.created_at}"

    # def no_item_in_cart(self):
    #     self.no_ord_cart = OrderItem.objects.filter(user=self.request.user,ordered=False)
    #     return self.no_ord_cart

    def get_total_item_price(self):
        return self.quantity * self.item.p_price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.p_dis_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.p_dis_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()

    class Meta:
        ordering = ['-created_at']
# vAe1x741Tf
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="cartitems")
    ref_code = models.CharField(max_length=20,null=True,blank=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    address = models.ForeignKey('Address', on_delete=models.SET_NULL, null=True, blank=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, null=True, blank=True)
    coupon = models.ForeignKey('CouponCode', on_delete=models.SET_NULL, null=True, blank=True)
    being_delivered = models.BooleanField(default=False)
    recieved = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_requested_reason = models.CharField(max_length=200, null=True, blank=True)
    refund_granted = models.BooleanField(default=False)
    track_order = models.CharField(max_length=80, null=True, blank=True)
    
    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon and total>1:
            total -= self.coupon.amount
        return total 

class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    phone_n = models.IntegerField(null=True)
    street_address = models.CharField(max_length=200,null=True)
    state = models.CharField(max_length=50,null=True)
    city = models.CharField(max_length=50,null=True)
    pin_code = models.CharField(max_length=6,null=True)

    def __str__(self):
        return self.street_address

    class Meta:
        verbose_name_plural = 'Addresses'


class CouponCode(models.Model):
    code = models.CharField(max_length=15, unique=True)
    valid_from = models.DateTimeField(null=True, blank=True)
    valid_to = models.DateTimeField(null=True, blank=True)
    amount = models.FloatField()
    active = models.BooleanField(default=True)
    used = models.IntegerField(default=0)

    def __str__(self):
        return self.code

class metaTags(models.Model):
    keyword = models.TextField()
    desc = models.TextField()

    def __str__(self):
        return "Keywords:" + self.keyword

class Review(models.Model):
    image = models.ImageField(upload_to="Customer_review")
    name = models.CharField(max_length=50)
    desc = models.CharField(max_length=300)
    
    def __str__(self):
        return self.name


class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.IntegerField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}"

class EmailNewsletter(models.Model):
    email = models.CharField(max_length=60)
    def __str__(self):
        return self.email

class About(models.Model):
    desc = models.TextField()
    
    def __str__(self):
        return self.desc

class EcomfashionContactDetails(models.Model):
    address = models.TextField()
    phone_num = models.CharField(max_length=50)
    gmail = models.CharField(max_length=50)

    def __str__(self):
        return self.gmail

class ContactUs(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    phone_num = models.CharField(max_length=11)
    message = models.TextField()

    def __str__(self):
        return f"{self.name} {self.phone_num}"

class PrivacyPolicy(models.Model):
    desc = models.TextField()

class TermsCondition(models.Model):
    desc = models.TextField()

class ReturnPolicy(models.Model):
    desc = models.TextField()

products/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CheckoutForm(forms.Form):
	street_address = forms.CharField(required=False)
	address_line2 = forms.CharField(required=False)
	state = forms.CharField(required=False)
	city = forms.CharField(required=False)
	pin_code = forms.CharField(required=False,max_length=6)
	set_default_address = forms.BooleanField(required=False)
	use_default_address = forms.BooleanField(required=False)
	# payment_option = forms.ChoiceField(widget=forms.RadioSelect,choices=PAYMENT_METHOD)


# class CouponForm(forms.Form):
# 	code = forms.CharField(label='',widget=forms.TextInput(attrs={
# 		'class': 'form-control',
# 		'placeholder': 'Promo code',
# 		'aria-label':"Recipient's username",
# 		'aria-describedby':"basic-addon2"
# 	}))

products/templates/about.html
{% extends 'base.html' %}
{% block title %}About Us - EfashionBazaar{% endblock title %}
{% block mainCont %}
<section class="contactUs">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <span>About US</span>
                    <h2>Get in touch with us</h2>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="aboutUs">
    <div class="container">
        <p class="aboutUsDetails">
            {% for i in about %}
            {{ i.desc }}
            {% endfor %}
        </p>
    </div>
</section>
{% include 'footer.html' %}
{% endblock mainCont %}

products/templates/base.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% for i in tag %}
  <meta name="description" content="{{ i.keyword }}">
  <meta name="keywords" content="{{ i.desc }}">
  {% endfor %}
  <link rel="icon" href="{% static 'image/logo.png'%}" sizes="16x16 32x32" type="image/png">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Custon CSS Link  -->
  <link rel="stylesheet" href="{% static 'css/itsmystyle.css' %}">
  <!-- LOGO  -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <title>{% block title %} {% endblock title %}</title>
</head>

<body>
  <!-- Navbar Begins  -->
  <nav class="navbar navbar-expand-sm navbar-dark" id="navbarId">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'landing' %}">eFashionBazar</a>
      <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
        aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fa fa-stream sidebarlogo" aria-hidden="true"></i>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <a class="nav-link navAnchorItem" href="{% url 'landing' %}#MenparticularCategoriesSecId">MEN</a>
          </li>
          <li class="nav-item">
            <a class="nav-link navAnchorItem" href="{% url 'landing' %}#WomenparticularCategoriesSecId">WOMEN</a>
          </li>
          <li class="nav-item">
            <a class="nav-link navAnchorItem" href="{% url 'landing' %}#KidsparticularCategoriesSecId">KIDS</a>
          </li>
          <li class="nav-item d-none d-sm-block">
            <a class="nav-link navAnchorItem" data-toggle="collapse" href="#searchItem" role="button"
              aria-expanded="false" aria-controls="searchItem">
              <i class="fa fa-search cartlogo" aria-hidden="true"></i>
            </a>
          </li>
          <li class="nav-item d-sm-none">
            <a class="nav-link navAnchorItem" data-toggle="collapse" href="#searchItem" role="button"
              aria-expanded="false" aria-controls="searchItem">
              Search <i class="fa fa-search cartlogo" aria-hidden="true"></i>
            </a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item d-sm-none">
            <a class="nav-link carLogoAnchor" href="/cart/">
              <span>Cart</span><i class="fa fa-opencart cartlogo" aria-hidden="true"></i>
            </a>
          </li>
          <li class="nav-item d-none d-sm-block">
            <a class="nav-link carLogoAnchor navAnchorItem" href="/cart/">
              {% if request.user.orderitems.all %}
              <span class="badge badge-warning">
                {{ request.user.orderitems.count }}
              </span>
              {% endif %}

              <i class="fa fa-opencart cartlogo" aria-hidden="true"></i>
            </a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-display="static" id="navbarDropdown" role="button"
              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-user cartlogo" aria-hidden="true"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-sm-right" aria-labelledby="navbarDropdown">

              {% if user.is_authenticated %}
              <a class="dropdown-item" href="{% url 'myorder' %}">Hi {{ user|capfirst }}</a>
              <a class="dropdown-item" href="{% url 'myorder' %}">My Orders</a>
              <a class="dropdown-item" href="{% url 'track' %}">Track Order</a>
              <a class="dropdown-item" href="{% url 'return' %}">Return/Refund</a>
              <a class="dropdown-item" href="{% url 'about' %}">About Us</a>
              <a class="dropdown-item" href="{% url 'contact' %}">Contact Us</a>
              <a class="dropdown-item" href="{% url 'policy' %}">Privacy Policy</a>
              <a class="dropdown-item" href="{% url 'returnPolicy' %}">Return/Refund Policy</a>
              <a class="dropdown-item" href="{% url 'terms' %}">T&C</a>
              <div class="dropdown-divider"></div>
              <form method="post" action="{% url 'account_logout' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-link dropdown-item">Logout</a>
              </form>
              {% else %}
              <a class="dropdown-item" href="{% url 'about' %}">About Us</a>
              <a class="dropdown-item" href="{% url 'contact' %}">Contact Us</a>
              <a class="dropdown-item" href="{% url 'policy' %}">Privacy Policy</a>
              <a class="dropdown-item" href="{% url 'returnPolicy' %}">Return/Refund Policy</a>
              <a class="dropdown-item" href="{% url 'terms' %}">T&C</a>
              <a class="dropdown-item" href="{% url 'account_login' %}">Login | Signup</a>
              {% endif %}
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- Navbar Ends  -->
  <!-- Search Begins -->
  <div class="collapse" id="searchItem">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 offset-lg-2 col-12">
          <form action="{% url 'search' %}" method="GET">
            <div class="input-group blogBar mt-3 mb-3">
              <input type="search" class="form-control searchInput" name="search" placeholder="Search Products"
                required>
              <div class="input-group-append">
                <input class="input-group-text subscribeText" type="submit" value="Search">
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- Search Ends -->
  {% include 'messages.html' %}
  {% block mainCont %}{% endblock mainCont %}
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/7a10e3388d.js" crossorigin="anonymous"></script>
  <script type="text/javascript"
    src="https://platform-api.sharethis.com/js/sharethis.js#property=606dd63d9269c20011a2a36c&product=sticky-share-buttons"
    async="async"></script>
  {% block jsCont %}{% endblock jsCont %}
  <script src="{% static 'js/topFunc.js' %}"></script>
  <script src="{% static 'js/copyrightYear.js' %}"></script>
</body>

</html>

products/templates/contact.html
{% extends 'base.html' %}
{% block title %}Contact Us - EfashionBazaar{% endblock title %}
{% block mainCont %}
<!-- Contact Us Begins Here  -->
<section class="contactUs">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <span>Contact US</span>
                    <h2>Get in touch with us</h2>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="contactUsMain">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="section-title contact-title">
                    <span>Contact Us</span>
                    <h2>Quick Touch</h2>
                </div>
                {% for i in contact %}
                <div class="contact-widget">
                    <div class="contactUsIcons">
                        <i class="fa fa-map-marker-alt"></i>
                        <p>{{i.address}}</p>
                    </div>
                    <div class="contactUsIcons">
                        <i class="fa fa-mobile-alt"></i>
                        <ul>
                            <li>{{i.phone_num}}</li>
                        </ul>
                    </div>
                    <div class="contactUsIcons email">
                        <i class="fa fa-envelope"></i>
                        <p>{{ i.gmail }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="col-lg-6">
                <div class="leave-comment">
                    <h5>Leave a message</h5>
                    <form action="" method="POST">
                        {% csrf_token %}
                        <input type="text" placeholder="Name" name="submitter_name" required>
                        <input type="text" placeholder="Email" name="submitter_email" required>
                        <input type="text" placeholder="Phone Number" name="phone_num" required>
                        <textarea placeholder="Leave any query" name="message"></textarea>
                        <button type="submit">Submit</button>
                    </form>
                </div>
            </div>
        </div>
        <!-- <div class="map">
        <iframe
          src="https://www.google.com/maps/embed/v1/place
          ?key=AIzaSyD7HG4-hxObd_WtkmZiE3ZlL6D0ZZ0OcJU"
          height="550" style="border:0;" allowfullscreen=""></iframe>
      </div> -->
    </div>
</section>
<!-- Contact Us Ends Here  -->
{% endblock mainCont %}

products/templates/footer.html
<!-- Footer Begins Here  -->
<section class="footerId">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-4 col-sm-6 col-12 justify-content-center text-center footer-div">
        <h4 class="footerH4">eFashionBazar</h4>
        <p class="text-white">
          {% for i in about %}
          {{ i.desc|slice:"0:162" }}
          {% endfor %}...
          <a href="{% url 'about' %}"> Read More</a>
        </p>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-6 col-12 justify-content-center text-center footer-div">
        <h4 class="footerH4">Navigation links</h4>
        <li><a href="{% url 'landing' %}#MenparticularCategoriesSecId">Men</a></li>
        <li><a href="{% url 'landing' %}#WomenparticularCategoriesSecId">Women</a></li>
        <li><a href="{% url 'about' %}">About Us</a></li>
        <li><a href="{% url 'contact' %}">Contact Us</a></li>
        <li><a href="{% url 'policy' %}">Privay Policy</a></li>
        <li><a href="{% url 'terms' %}">Terms and Condition</a></li>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-12 col-12 justify-content-center text-center footer-div">
        <h4 class="footerH4">Social Links</h4>
        <li><a class="fbitext" href="#">Facebook <i class="fab fa-facebook-f fbi" aria-hidden="true"></i></a>
        </li>
        <li><a class="twitext" href="#">Twitter <i class="fab fa-twitter twi" aria-hidden="true"></i></a>
        </li>
        <li><a class="insitext" href="#">Instagram <i class="fab fa-instagram insi" aria-hidden="true"></i></a></li>
      </div>
    </div>
    <div class="mt-4 text-center">
      <p class="text-white">Copyright <i class="far fa-copyright" aria-hidden="true"></i>
        2012-
        <span id="copyrightYear"></span> | All Right Reserved. Developed with <i class="fa fa-heart loveRC"
          aria-hidden="true"></i> by
        <a href="https://www.ripechilli.com" target="_blank" id="RipeChilli">RipeChilli</a> .
      </p>
    </div>
    <div class="scrolltop float-right">
      <i class="fa fa-arrow-up" id="myBtn"></i>
    </div>
  </div>
</section>
<!-- Footer Ends Here  -->

products/templates/index.html
{% extends 'base.html' %}
{% block title %}Home - EfashionBazaar{% endblock title %}
{% block mainCont %}
{% load static %}
<!-- MainBanner Begins  -->
<section class="mainBanner">
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      {% for i in crousal %}
      <div class="carousel-item {% if forloop.first %}active{% endif %}">
        <img src="{{i.img.url}}" class="d-block mainBannerImages" alt="{{ i.title }}">
      </div>
      {% endfor %}
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</section>
<!-- MainBanner Ends  -->
<!-- Categories Begins  -->
<section class="categoriesSec">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-12">
        <hr class="style5">
        <p class="text-center categoriesMainTitle">
          Categories
        </p>
      </div>
    </div>
    <div class="row">
      {% for i in available_for %}
      <div class="col-lg-4 col-12">
        <a href="#{{i.title}}particularCategoriesSecId">
          <div class="categoriesCard">
            <img src="{{i.img.url}}" class="img-fluid categoriesCardImage" alt="">
            <p class="text-center categoriesCardTitle">
              {{i.title}}
            </p>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- Categories Ends  -->
<!-- Particular Categories Begins  -->
{% for i in available_for %}
<section class="particularCategoriesSec" id="{{i.title}}particularCategoriesSecId">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-12">
        <hr class="style5">
        <p class="text-center categoriesMainTitle">
          {{i.title}}
        </p>
      </div>
    </div>
    <div class="row">
      {% for j in i.category_set.all %}
      <div class="col-lg-3 col-md-6 col-6">
        <a href="{% url 'category' j.id %}">
          <div class="particularCategoriesCard">
            <img src="{{j.poster.url}}" class="img-fluid particularCategoriesCardImage" alt="">
            <p class="text-center particularCategoriesCardTitle">
              {{j.title}}
            </p>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endfor %}

<!-- Particular Categories Ends  -->
<!-- Reviews Begins  -->
<section class="reviews">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-12">
        <hr class="style5">
        <p class="text-center categoriesMainTitle">
          Customer Reviews
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12 col-12">
        <div id="carouselExampleControls" class="carousel slide carousel-fade" data-ride="carousel">
          <div class="carousel-inner justify-content-center text-center">
            {% for i in review %}
            <div class="carousel-item {% if forloop.first %}active{% endif %}">
              <img src="{{ i.image.url }}" class="img-fluid img-rounded reviewImages" alt="efashionbazar">
              <p class="review_title">
                {{ i.name }}
              </p>
              <p class="review_para">
                "{{ i.desc }}"
              </p>
            </div>
            {% endfor %}
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Reviews Ends  -->
<!-- NewsLetter Begins -->
<section class="newsLetter">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-12">
        <hr class="style5">
        <p class="text-center categoriesMainTitle">
          Subscribe Newsletter
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-8 offset-lg-2 col-12">
        <form method="POST">
          {% csrf_token %}
          <div class="input-group blogBar">
            <input type="email" class="form-control searchInput" name="email" placeholder="Your Email" required>
            <div class="input-group-append">
              <input type="submit" class="input-group-text subscribeText" value="Subscribe">
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
<!-- NewsLetter Ends -->
{% include 'footer.html' %}
{% endblock mainCont %}

products/templates/messages.html
{% if messages %}
<div class="alert alert-success alert-dismissible fade show">
  <strong>{% for i in messages %} {{ i }} {% endfor %}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}